name: NPanel
version: 2024.12-beta.1
api-version: 1.21
description: Adds a web panel to a minecraft server.
authors: [jmurth1234,danieldieeins,nerotvlive]
author: nerotvlive
load: STARTUP

main: live.nerotv.npanel.PanelPlugin
softdepend: [Vault]

commands:
  jpanel:
    description: Information about the current NPanel install
    usage: /<command>
  addlogin:
    description: Adds a user to NPanel
    usage: /<command> [username] [password]
  passwd:
    description: Change the password for a NPanel user
    usage: /<command> [username] [oldpassword] [newpassword]